### PR TITLE
Fix crashes caused by toasts on API < 30

### LINKED ISSUE #1618: [v1.34.1] Process crashes when custom toast is shown - java.io.IOException: Command failed (tcp:7001): closed
**Describe the bug**
The process crashes after Android toast is shown.  **Only happens for custom toast(i.e. with custom view)**
```
Exception in thread "pool-4-thread-1" java.io.IOException: Command failed (tcp:7001): closed
	at dadb.adbserver.AdbServer.send$dadb(AdbServer.kt:99)
	at dadb.adbserver.AdbServerDadb.open(AdbServer.kt:138)
	at dadb.forwarding.TcpForwarder.handleForwarding$lambda-1(TcpForwarder.kt:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**To Reproduce**
when the `-tapOn: Show toast` command is executed (i.e. a Android toast is shown), the whole process crashes.
```
name: Test toast
appId: com.myapp
---
- launchApp:
    clearState: true
- tapOn: Show toast
- tapOn: Next
```

**Expected behavior**
The flow runs without crash

**Screenshots**

**Environment information (please complete the following information):**

- Maestro version [v1.34.1]
- Platform: [Android 13]
- Framework: [Native Android]
- Device model and OS version: [vivo Y76 5G]
- Physical device
- Host [Mac M1]

### PR DESCRIPTION
**Pull request by NyCodeGHG**
## Proposed Changes

This PR fixes maestro crashes occuring on APi < 30 caused by toasts.
AccessibilityNodeInfo's constructor is only available on API 30 and up, so we use `AccessibilityNodeInfo.obtain()` instead on lower API levels.

## Testing
I ran [a simple test app](https://github.com/NyCodeGHG/ToastTest) which creates a toast on API 29 with [this flow](https://github.com/NyCodeGHG/ToastTest/blob/main/test-flow.yml).

## Issues Fixed
#1618

### CODE REVIEW

**Comment by jaychang0917** [comment]
@NyCodeGHG but the version i used is API 33.

**Comment by NyCodeGHG** [comment]
@jaychang0917 that's weird, the API should exist on that API level. I'll have another look!

**Comment by NyCodeGHG** [comment]
@jaychang0917 I can't reproduce your issue, do you have any logcat logs from the android device?

**Comment by LisandroDiMeo** [comment]
Had this issue and this solved it. Thanks!

**Comment by axelniklasson** [comment]
@NyCodeGHG can you provide the binary for the `ToastTest` app so I can test it locally without having to build the project? Running into some dependency issues which I don't have bandwidth to dig into at the moment. Thanks!

**Comment by NyCodeGHG** [comment]
@axelniklasson sure, here is a debug build of the app:
(in a tar.gz archive because github doesn't allow uploading raw apk files)
[ToastTest.tar.gz](https://github.com/mobile-dev-inc/maestro/files/14137420/ToastTest.tar.gz)

**Comment by frichez** [comment]
Also had this issue and this solved it. I hope it will be merged soon. Thanks!

**Comment by axelniklasson** [comment]
Thanks @NyCodeGHG -- can confirm that this fixes the bug resulting in the crash. We appreciate the contribution 👏

**Review by axelniklasson — APPROVED** [review]

**Pull request merged**
