### PR TITLE
Fix wrong error message

### LINKED ISSUE #1623: Wrong error message in cli with format+continuous flags
**Describe the bug**
When running maestro test with --format and --continuous flag, the error message is wrong

**To Reproduce**
1. Run `maestro test --format junit --continuous Flow.yaml`
2. The error message says `Continuous mode is not supported for directories. Flow.yaml is a directory`

**Expected behavior**
The error message should say `format can not be specified in continuous mode`

**Screenshots**
image

**Environment information (please complete the following information):**

- Maestro version 1.34.2 (self-compiled from develop)
- Platform: Android
- Framework: n.A.
- Device model and OS version: n.A.
- Host Manjaro Linux

**Workspace (if applicable)**
n.A.

**Bugreport output (if applicable)**
n.A.

**Additional context**
`maestro test --format junit Flow.yaml` works fine and
`maestro test --continuous Flow.yaml` works fine but the combination 
`maestro test --format junit --continuous Flow.yaml` has a misleading error message.

### PR DESCRIPTION
**Pull request by tokou**
## Proposed changes

- Change the error message depending on the above condition

## Testing

- `./gradlew test`
- `./maestro-cli/build/install/maestro/bin/maestro test --format=JUNIT --continuous flow.yaml`

## Issues fixed

Fixes #1623

### CODE REVIEW

**Review by bartekpacia — APPROVED** [review]
a test seems to be failing, please fix it

**Review by bartekpacia — CHANGES_REQUESTED** [review]
test if failing

**Comment by bartekpacia** [comment]
Works fine now. Thanks a ton @tokou!

**Review by bartekpacia — APPROVED** [review]

**Comment by tokou** [comment]
Thanks for fixing the small issue here @bartekpacia

**Pull request merged**
