### PR TITLE
Use XCTest for tapping on iOS

### PR DESCRIPTION
**Pull request by berikv**
## Proposed Changes

Use XCTest for tapping on iOS

### CODE REVIEW

**Review by dmitry-zaitsev — APPROVED** [review]

**Comment by berikv** [comment]
> Can we use IDB as a fallback just in case?

I'd rather go for no-idb directly

**Comment by dmitry-zaitsev** [comment]
We are risking to break this for every user of Maestro, let's do it safely and add a fallback

**Comment by amanjeetsingh150** [comment]
> Can we use IDB as a fallback just in case?
@dmitry-zaitsev last I remember adding private apis have resolved for long screens/react native as well. Do we still know any failure cases?

**Comment by berikv** [comment]
As discussed offline, will first run an extensive test before merging

**Pull request merged**
