### PR TITLE
Handle multiple flow files in test command

### LINKED ISSUE #1990: [Feature Request] Accept comma separated list of flows or flow directories
### Use case

Right now, the `flowFile` option of the CLI expects either a flow file path `flows/some_feature/some_flow.yml` or a flow directory path `flows/other_feature/`.

However I often run into cases where I want to run 2 sets of flow files (or more), but not the whole test suite.
Example: making sure a certain feature did not introduce regressions in another closely related feature.

Here's what happens when I do that:

```
> maestro test flows/some_feature/some_flow.yml,flows/other_feature/

Flow path does not exist: $SRC/e2e/flows/some_feature/some_flow.yml,flows/other_feature/
```

### Proposal

I'd like for `flowFile` to accept a comma-separated list of flow files or directories and to construct the flows to run as the union of all of those.

Basically: 

```
maestro test flows/some_feature/some_flow.yml,flows/other_feature/
```

Would be kinda like:

```
maestro test flows/some_feature/some_flow.yml

maestro test flows/other_feature/
```

### Anything else?

This is similar to the current behavior of `--device`

### PR DESCRIPTION
**Pull request by tokou**
## Proposed changes

- I opted for a space separated list as it's an argument and not an option
- I only affected test command and tried to have no effect on other commands

## Testing

- Added test cases in `WorkspaceExecutionPlanner`

## Issues fixed

Fixes #1990

### CODE REVIEW

**Comment by bartekpacia** [comment]
Thanks, this looks nice!

I'm curious if tab-completion works when the user wants to pass a few space-delimeted yaml files?

**Comment by tokou** [comment]
Yes it works

**Comment by bartekpacia** [comment]
Looks like test failed because `ccorrect@mobile.dev` was entered instead of `correct@mobile.dev`. 

screenshot-❌-1725115883738-(Fill out form)

Weird issue, I assume it's some random flakiness. I skimmed over existing bugs but didn't find an existing issue for it.

Action taken: rerun the test.

**Comment by bartekpacia** [comment]
@tokou there's a conflict now after we've merged #1945

**Comment by bartekpacia** [comment]
LGTM, thanks!

**Pull request merged**
