### PR TITLE
Add support for multipart form data file upload

### PR DESCRIPTION
**Pull request by maciejkrolik**
## Proposed Changes

This PR adds support for multipart form data file upload.

By using this feature I can prepare data on the backend before running e2e tests on mobile.

Usage is simple. Instead of a `body` object we can define `multipartForm` with as many fields as we want. We can also upload multiple files in one request by using many objects with `filePath` properties. Both `filePath` and `mediaType` are required for files. If `multipartForm` is available in request then `body` will be ignored.

### Example script
``` js
function uploadFile() {
  const filePath = ``;
  const url = ``;

  const response = http.post(url, {
    multipartForm: {
      "uploadType": "test",
      "data": {
        "filePath": filePath,
        "mediaType": "text/csv"
      }
    },
    headers: {
      'Content-Type': 'multipart/form-data',
      'Authorization': `Bearer ${token}`
    },
  });
}
```

## Testing
 - Integration + unit tests
 - Manual testing

### CODE REVIEW

**Comment by axelniklasson** [comment]
Thanks for raising this PR @maciejkrolik! 

In order for us to move ahead, could you please update with the following?
- Add support for multipart upload in [GraalJsHttp](https://github.com/mobile-dev-inc/maestro/blob/main/maestro-client/src/main/java/maestro/js/GraalJsHttp.kt)
- Provide a test case (for example using the Wikipedia app and a Flow) showing that using request body still works as intended
- Raise a PR with documentation updates in https://github.com/mobile-dev-inc/maestro-docs?

Thanks!

**Comment by axelniklasson** [comment]
Following up here - I see that you also updated GraalJsHttp, nice! Could you extract the repeated code into shared functions and also add test cases? Then it should be good to go :)

**Comment by axelniklasson** [comment]
Closing this out due to inactivity -- @maciejkrolik, let me know if you plan on addressing the final comments and I'll reopen it :)

**Comment by maciejkrolik** [comment]
@axelniklasson Could you reopen the PR, please? :) I've addressed all the comments by:
- adding support for GraalJsHttp 
- cleaning up the code and moving common functions to HttpUtils
- adding some unit tests and one integration test (if you think something more is needed, let me know)

Today I'm going to create a PR with updated docs :)

**Comment by axelniklasson** [comment]
@maciejkrolik That's awesome! I do howevery believe you need to open a new PR as GitHub doesn't allow reopening this PR:

image

**Comment by maciejkrolik** [comment]
@axelniklasson New PR ready https://github.com/mobile-dev-inc/maestro/pull/1474

**Pull request closed without merging**
