### PR TITLE
Update graaljs

### LINKED ISSUE #1388: Update GraalJS engine to latest version
**Is your feature request related to a problem? Please describe.**
Currently the version used seems to be 22.0.0

Check:
https://github.com/mobile-dev-inc/maestro/blob/5fcec04d7d52e0134a934605082a92829e7e6981/gradle/libs.versions.toml#L29

As you can see here, a lot of cool stuff has been implemented: https://github.com/oracle/graaljs/blob/master/CHANGELOG.md

Take a look here too:
https://github.com/oracle/graaljs/blob/master/docs/user/JavaScriptCompatibility.md

If I try to run the following code with the current version it doesn't work, there are some things I would like to try, I don't even know if they work with the latest current version.
```js
var BigDec = Java.type('java.math.BigDecimal');
var bd = new BigDec("0.1");
console.log(bd.add(bd).toString());
```

**Describe the solution you'd like**
Update the version to the latest.

### PR DESCRIPTION
**Pull request by tokou**
## Proposed changes

- Update GraalJs
- Enable host access and class lookup

## Testing

- Update integration test 102 to add running the sample script

## Issues fixed

Fixes #1388

### CODE REVIEW

**Comment by bartekpacia** [comment]
Hey, thanks a lot @tokou! Unfortunately we're not ready to bump GraalJS just yet, because Maestro targets Java 8, and we don't want to bump it. Our analytics show many our users still use it, despite it being EOL.

**Comment by bartekpacia** [comment]
Closing because of reasons given above.

**Comment by tokou** [comment]
@bartekpacia Thanks for the clarification
How can I run a test locally to ensure that the app behaves correctly on Java 8 or not?

**Comment by bartekpacia** [comment]
We are setting `-Xjdk-release` arg for Kotlin compiler ([example here](https://github.com/mobile-dev-inc/maestro/blob/0357b5ef595ad77bd19c0cc1b8f1ad2b9e268bb4/maestro-cli/build.gradle.kts#L69-L73)) so right now as long as the project builds fine then the Maestro CLI should also work. More on this topic:
- [Gradle toolchains are rarely a good idea](https://jakewharton.com/gradle-toolchains-are-rarely-a-good-idea/)
- [Kotlin's JDK release compatibility flag](https://jakewharton.com/kotlins-jdk-release-compatibility-flag/)

`./gradlew test`

**Pull request closed without merging**
