### PR TITLE
Rewrite `build.gradle` of `maestro-cli` to Gradle Kotlin DSL

### PR DESCRIPTION
**Pull request by bartekpacia**
## Proposed Changes

Basically the title.

## Testing

Gradle sync in IDE succeeds.

`$ ./gradlew :maestro-cli:build` passes.

## Issues Fixed

This is a small step towards #997.

I think having a single PR per migrated `build.gradle` is sensible. But if you prefer to have all `build.gradle`s migrated in a single PR, then that's not a problem as well.

### CODE REVIEW

**Comment by axelniklasson** [comment]
Thanks for this PR @bartekpacia! This took some time for us to take a look at this so there is now a merge conflict, but if you could go ahead and rebase I'll help get this merged.

**Comment by bartekpacia** [comment]
Rebased.

The merge conflicts were because of changes minor changes to `maestro-cli/build.gradle` made in #1172.

**Comment by bartekpacia** [comment]
Looking into test failures now.

**Review by axelniklasson — APPROVED** [review]
Thanks for the contribution @bartekpacia 🙌

**Pull request merged**
