### PR TITLE
Retry flows on failure

### PR DESCRIPTION
**Pull request by carlosmuvi**
## Proposed Changes

- Include `retryTestsCount` config param to auto-retry a flow instead of failing when a command execution does not succeed.

## Testing
- Create a flow with failing commands that includes `retryTestsCount` in its config. Tests should auto retry as many times as specified.
- No retries should happen if this config field is not provided.

## Issues Fixed
- https://github.com/mobile-dev-inc/maestro/issues/1124

### CODE REVIEW

**Comment by igorsmotto** [comment]
Hi @carlosmuvi,

While I appreciate the effort and thought put into this feature, I have decided to close the pull request as it doesn't align well with our current requirements.

The main reasons for closing it are:

- Achieving the same functionality without this feature is possible by creating a script that reads the response of Maestro tests and reruns Maestro as needed. We believe that implementing a separate configuration parameter for retries could be redundant in this context.
- The introduction of this feature could potentially hide flakiness in the local execution of Maestro, which could make flow code from users less robust. While we understand that flakiness can have various causes, we believe that it's important to address and minimize them directly rather than relying heavily on retries.

I appreciate your efforts in contributing to the project, and I encourage you to continue exploring other opportunities to enhance Maestro. If you have any questions or need further clarification regarding the decision to close the PR, please feel free to reach out to me.

Thank you for your understanding.

**Comment by omegasoft7** [comment]
@igorsmotto 

That is actually a good feature to have in Maestro.
Regarding the flakiness, lets the users decide what they need to have
and regarding implementing it via a script, imagine that I have a flow that contains 10 flows inside it. If I want to manage it with scripts, then in case of failures I have to run everything from the beginning, but if Maestro can handle it, then for instance if flow number 6 failed, I can only retry that flow once more, instead of everything again.
It would be great if you can consider having these functionalities at least for runFlow

Thanks

**Comment by freak4pc** [comment]
Sorry for the bump but I highly disagree this isn't needed - The point isn't retrying the entire flow which can be mostly simple in shell, but it's also to retry the specific tests which failed, which means parsing the results of the test report and then having the script retry only those failures. Seems like something that could be really nice to have in the tool instead of everyone writing their own.

**Comment by saihemanth121** [comment]
@igorsmotto Maestro Cloud supports test [retries](https://cloud.mobile.dev/reference/retries), doesn't it? Is it a lot different from the retry strategy being added here?

**Pull request closed without merging**
