### PR TITLE
Bump grpc to latest

### PR DESCRIPTION
**Pull request by berikv**

### CODE REVIEW

**Comment by SubhrajyotiSen** [comment]
This will also fix building from source on Apple Silicon

**Comment by alishari** [comment]
@dmitry-zaitsev I think this will fix the build issue on M1 laptops, I was unable to build the project and upgraded `grpc` on my code and it works.

**Review by dmitry-zaitsev — APPROVED** [review]

**Comment by dmitry-zaitsev** [comment]
@berikv let's make sure to update Maestro Cloud repo once this is released

**Comment by berikv** [comment]
Verified to work with both android and iOS

**Pull request merged**
