### PR TITLE
Adding a label field for some commands - you can optionally specify for this text to appear in your log/command display.

### PR DESCRIPTION
**Pull request by SuperRoach**
## Proposed Changes

To add in the ability to put a custom label seen when a test is running instead of the default description value.

### CODE REVIEW

**Comment by Fishbowler** [comment]
I've had a play locally and found some additional plumbing required to get this closer to the finish line.
`label` needs adding to the YamlElementSelector, and to each command's implementation in YamlFluentCommand.

If you add me as a collaborator on your fork, I'm happy to try to lend a hand directly?
Alternatively, I've added my patch file as an attachment. It works for `tapOn` only at this stage, but I was able to prove that I saw appropriate output in the terminal.
[e8b907.patch](https://github.com/mobile-dev-inc/maestro/files/12177272/e8b907.patch)

**Comment by Fishbowler** [comment]
I've moved this on a little further this morning with some additional plumbing for other commands and some tests. It's not finished, but you can see the state here:

https://github.com/mobile-dev-inc/maestro/compare/main...Fishbowler:maestro:FEAT-custom-labels

For now, I've reverted some of the labels you added - it'd take some refactoring to get in things like InputText, where there isn't an object in YamlFluentCommand - it's just a string.

**Comment by SuperRoach** [comment]
Revisiting this now and seeing if anything further is needed - I'll add you as a collaborator.

**Comment by Fishbowler** [comment]
I've moved it along in #1292, hoping to get some feedback, but things are expectedly a little slower in the northern hemisphere's summer months.

No objections if you want to fast forward this PR to that one and we can continue here?

**Comment by igorsmotto** [comment]
Closing in favor of https://github.com/mobile-dev-inc/maestro/pull/1292

**Pull request closed without merging**
