### PR TITLE
Add filename to env

### LINKED ISSUE #1616: Make the filename of the current test available as environment variable
Hi, is there a way to get the running test's filename?
one of the use case is I want to name the recording as same as the name of the file so that when I run multiple tests I don't have to worry for overwritten recording name

```
- startRecording: ${FILENAME}
```

### PR DESCRIPTION
**Pull request by tokou**
## Proposed changes

- Set `FILENAME` env value to the flow file's name
- This happens only in the context of the test and does not alter the system env

## Testing

I updated 2 of the integration tests to use the `FILENAME` env var and check their correct naming

Run ./gradlew :maestro-test:test
Run ./gradlew :maestro-orchestra:test
Run ./gradlew :maestro-orchestra-models:test

## Issues fixed

Fixes #1616

### CODE REVIEW

**Comment by bartekpacia** [comment]
Hey, thanks a ton Tarek. Overall this LGTM!

Two small things:
- let's change name to `MAESTRO_FILENAME`
- how does it behave in subflows? Is the name of the root flow printed? Is there any difference between JS engines?

PS In the longer term, I think we'll need to have a list of all Maestro-provided env variables, so people will not override them when they pass their own `MAESTRO_FILENAME` vars.

**Review by bartekpacia — APPROVED** [review]

**Comment by bartekpacia** [comment]
@tokou I rebased with master (to make github checks ✅) and renamed the variable.

If you have some free time (and will!), tests would be great to see:)

**Comment by tokou** [comment]
I noticed with the tests that we populate the env var with subflow file names in the subflows. I think it makes more sense for it to always be the top level flow name. So I fixed it and added some tests.

**Comment by bartekpacia** [comment]
> I think it makes more sense for it to always be the top level flow name.

Agreed, thanks a ton!

After the conflicts are resolved this is good to go.

**Comment by bartekpacia** [comment]
One last ask, if I may - could we keep `withEnv()` the way it was before? To minimize changed lines + make code more explicit.

```
.withUserProvidedEnv()
.withSystemEnv(...)
```

makes it obvious that "system env vars" (like `MAESTRO_FILENAME`) take precedence – which is what we want.

Lmk what you think. You already did a lot and I don't want you to lose enthusiasm :)

**Comment by bartekpacia** [comment]
On the other hand, this is good enough. Thanks a lot!

**Pull request merged**
