### PR TITLE
[Feedback PR] Prepare maestro to make it easier to add new commands

### PR DESCRIPTION
**Pull request by ragunathjawahar**
Folks, I was looking at the issue list and was interested in implementing https://github.com/mobile-dev-inc/maestro/issues/100 and https://github.com/mobile-dev-inc/maestro/issues/105. This is an initial refactor PR towards that direction. If this looks good to you folks, we can explore simplifying `Orchestra.executeCommand`. After that, extending Maestro should be relatively easier. Let me know what you think.

Thank you and great job pulling this off.

### CODE REVIEW

**Review by dmitry-zaitsev — CHANGES_REQUESTED** [review]
I know that this seems like a straightforward thing to do, but there is one caveat that unfortunately makes this change not suitable for us (and I realise we should've left a comment about that) - we actually serialize `MaestroCommand` as JSON when using Maestro as part of our backend product (mobile.dev).

Thank you for taking your time and submitting the suggestion!

**Comment by ragunathjawahar** [comment]
Interesting, this is new information to me. I was wondering what the `MaestroCommand` is for. Now it makes sense. The goal I was aiming was this—how do we keep the system open for extension but closed for modification along the axis for adding or removing commands.

As you know, the compiler's feedback is something that we can use as a checklist to educate folks that want to add more commands. Do you mind if I take another stab at this? I will also add the required tests for the JSON serialisation. Anyways this is a feedback PR and I don't mind if the next set of changes don't make it either. I'd be a learning exercise for me.

**Comment by ragunathjawahar** [comment]
> we actually serialize MaestroCommand as JSON when using Maestro as part of our backend product (mobile.dev)

Ah... overlooked this bit. Closing this PR.

**Comment by dmitry-zaitsev** [comment]
> Do you mind if I take another stab at this? I will also add the required tests for the JSON serialisation. Anyways this is a feedback PR and I don't mind if the next set of changes don't make it either. I'd be a learning exercise for me.

As long as tests for serialization are in place - sure, go for it!

**Pull request closed without merging**
