### PR TITLE
chilfOf Selector added

### PR DESCRIPTION
**Pull request by sandeepjoshi19**
### <samp>🤖 Generated by Copilot at a0070d6</samp>

This pull request adds the `childOf` feature to the `ElementSelector` class and its YAML representation, which allows finding elements that are nested inside other elements. It also refactors the project structure and adds a new function to the `Maestro` class that uses the `childOf` feature to find an element from a view hierarchy.
Added support of `childOf`  selector which takes a `element node` as value. If we want to search a selector that is child of some view we can use this selector
`childOf: Element`

```
tapOn:
   text: "buy now"
    childOf:
        - id: "buy-now-button"


```

### CODE REVIEW

**Comment by axelniklasson** [comment]
Hi there @sandeepjoshi19 👋 Would be great to learn more about this use case and when you want to use a selector like this?

**Comment by saihemanth121** [comment]
@axelniklasson wanted to share one usecase where this would help me. This is my hierarchy
```
(LinearLayout)
    .
    .
    (LinearLayout) tv_post_like
	.
	.
	- (TextView) text_view
	.
	.
    (LinearLayout) tv_post_comment
	.
	.
	- (TextView) text_view
	.
	.
```

I want to copy text from the `text_view` inside `tv_post_like`. But I cannot use index or id selectors in `copyTextFrom` as index can change and id is not unique. But I can use `childOf: tv_post_like` selector to get my desired result.

**Comment by axelniklasson** [comment]
Thanks for that context @saihemanth121 👍 

@sandeepjoshi19 I'd be happy to help you get this merged. If you want to update with the following:
- Rebase on latest `main`
- Add tests

After that I'll be happy to take a look and review it!

**Comment by axelniklasson** [comment]
Hi there @sandeepjoshi19, just checking in here -- when are you planning on addressing the feedback? We're working on improving our "time to land" for community PRs to avoid them hanging for too long.

**Comment by axelniklasson** [comment]
Closing out due to inactivity from author. @sandeepjoshi19 let me know if you end up picking this up again and I'll be helping out to get it merged!

**Comment by sandeepjoshi19** [comment]
@axelniklasson Sorry was busy with some other work. I have rebased the code Please help me on Test.

**Pull request closed without merging**
