### PR TITLE
Add support to custom Android driver startup timeout

### PR DESCRIPTION
**Pull request by arildojr7**
## Proposed Changes
This PR adds possibility to specify a custom timeout for android driver startup and
add a logic to assure that instrumentation is working properly before proceed.

On slow environments, the shell command to start instrumentation was being executed before maestro apks and device get settle, meaning that the `dadb.open("tcp:7001").close()` would never work, causing a timeout exception.

## Testing
For who had problem to start maestro on CI/CD due a not enough timeout (like me), can set the env:
```
export MAESTRO_DRIVER_STARTUP_TIMEOUT=60000 // 60 sec
./maestro test flow.yaml
```

<details>
  <summary>To simulate a slow apk installation, apply this patch...
</summary>

```
Subject: [PATCH] add support to custom android driver startup timeout
---
Index: maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt b/maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
--- a/maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt	(revision c3eaf2aed2c0a3d65a1751adad5ded2c4f16073a)
+++ b/maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt	(date 1682800946007)
@@ -63,12 +63,14 @@
 import org.w3c.dom.Node
 import java.io.File
 import java.io.IOException
+import java.util.Timer
 import java.util.UUID
 import java.util.concurrent.CompletableFuture
 import java.util.concurrent.Executors
 import java.util.concurrent.TimeUnit
 import java.util.concurrent.TimeoutException
 import javax.xml.parsers.DocumentBuilderFactory
+import kotlin.concurrent.schedule
 
 class AndroidDriver(
     private val dadb: Dadb,
@@ -90,7 +92,9 @@
 
     override fun open() {
         uninstallMaestroApks()
-        installMaestroApks()
+        Timer("Installing", false).schedule(5000) {
+            installMaestroApks()
+        }
         startInstrumentationSession()
 
         try {
@@ -110,9 +114,11 @@
             "dev.mobile.maestro.test/androidx.test.runner.AndroidJUnitRunner &\n"
 
         while (System.currentTimeMillis() - startTime < getStartupTimeout()) {
+            println(">>> TRYING")
             instrumentationSession = dadb.openShell(instrumentationCommand)
 
             if (instrumentationSession.successfullyStarted()) {
+                println(">>> SUCCESS")
                 return
             }
 

```
</details>

## Issues Fixed
https://github.com/mobile-dev-inc/maestro/issues/965
https://github.com/mobile-dev-inc/maestro/issues/553

### CODE REVIEW

**Comment by felipevolpone** [comment]
@arildojr7 Thanks for opening a PR for that. However, this should be supported for all platforms (iOS, Android, and web). Could you expand your PR to cover that?

**Comment by arildojr7** [comment]
> 

of course, I will do it 😎

**Comment by arildojr7** [comment]
Another point
On slow environments, like CI/CD server, there is no time to device settle after maestro apks are installed and before run `instrumentationSession?.write()`.

It means that, since `instrumentationSession?.write()` didn't work correctly, `dadb.open("tcp:7001").close()` will never work, throwing a timeout exception as well.

Putting a Thread.sleep between this command solves this problem, so I will update it in a better way, for maestro to wait apks install and settle.

@felipevolpone

**Comment by k0shk0sh** [comment]
@felipevolpone can we get this PR merged if everything checks out? its a blocker for us.

**Comment by theinterlocker7** [comment]
This is awesome! Thanks @arildojr7 . Can we can some eyes on this, it'd be a blocker for us too.

@felipevolpone

**Comment by felipevolpone** [comment]
Adding @amanjeetsingh150 to help me here in the review as he knows more about this part of the code

**Comment by k0shk0sh** [comment]
@amanjeetsingh150 could you please have a look at this PR. Thanks.

**Review by amanjeetsingh150 — APPROVED** [review]
Curious what was the timeout that you had to set and for which CI?

**Comment by latorante** [comment]
@amanjeetsingh150 , for us, it just timed out, others (in other threads) manually adjusted the value and recompiled. The CI pipeline we use is in Github, and as others have pointed, the `macos-latest-xl` version does help, but not always feasible in all scenarios.

**Comment by amanjeetsingh150** [comment]
Thanks for the contribution @k0shk0sh @arildojr7 🙌  Can you also make a corresponding change in maestro docs: https://github.com/mobile-dev-inc/maestro-docs to improve the visibility of this configuration?

**Comment by latorante** [comment]
Hey hey @amanjeetsingh150 , @k0shk0sh , @felipevolpone .

Since this is approved and checks passing, what's the process in incorporating this PR and the docs PR https://github.com/mobile-dev-inc/maestro-docs/pull/10 and releasing it?

Thanks!

**Comment by arildojr7** [comment]
🥲

**Comment by axelniklasson** [comment]
Hi @arildojr7, quick update: Amanjeet is out on PTO and back next week and will follow up with you then.

**Comment by felipevolpone** [comment]
@arildojr7 Thank you for the contribution, well done 👏

**Pull request merged**
