### PR TITLE
feat: android pressKey - power button

### PR DESCRIPTION
**Pull request by depapp**
## Proposed Changes
add new `pressKey: power` command.

## Testing
```yaml
appId: com.google.android.youtube
---
- launchApp
- tapOn: Subscriptions
- pressKey: power #lock screen
- pressKey: power #unlock screen
```
https://github.com/mobile-dev-inc/maestro/assets/6134774/44f60ed2-1744-447a-87cc-a1c7a2206b14

## Issues Fixed
fix https://github.com/mobile-dev-inc/maestro/issues/1167

### CODE REVIEW

**Comment by felipevolpone** [comment]
Hey @depapp thank you very much for this PR 🙌  The Android part looks good, but we need to also support iOS. Would you be able to expand the PR to make that?

**Comment by depapp** [comment]
hi @felipevolpone thanks for the feedback.
since I couldn't find any APIs for the `physical power button` on iOS, I think it's not supported

**Comment by chriswiesner** [comment]
i would need support for the `menu` button (keycode: `82`) - probably also only available on Android.
Would be great if we could have support for keys which are android only 🙏

**Comment by depapp** [comment]
> @depapp Sorry for such a long delay in answering you back. Given that iOS doesn't support that, we can move forward with this PR. Could you please update with the latest `main` branch so we can run the tests again? As soon it's green I'll merge it.

done @felipevolpone 
could you please help to recheck 🙇🏻

**Review by felipevolpone — APPROVED** [review]

**Comment by felipevolpone** [comment]
Awesome work @depapp! Thanks for your contribution.

We are planning a Maestro release later this or early next week, either way in the next one this PR will be there

**Comment by depapp** [comment]
> Awesome work @depapp! Thanks for your contribution.
> 
> We are planning a Maestro release later this or early next week, either way in the next one this PR will be there

thanks @felipevolpone 🙇🏻

**Pull request merged**
