### PR TITLE
Update selenium and disable search engine choice screen

### LINKED ISSUE #1868: WebDriver: Disable search engine choice screen
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

Reproducible with any tests that uses the web driver when residing in a location for which Chrome shows the search engine selection screen.

### Actual results

With the latest version of Chrome, in some locations, a search engine selection screen modal will be shown and a search engine has to be selected before the browser can be used.

Screenshot 2024-08-01 at 12 21 50

### Expected results

The search engine selection screen should be skipped.

### About app

N/A

### About environment

* Version 127.0.6533.73 (Official Build) (x86_64)
* Location: Germany

### Logs

_No response_

### Maestro version

1.37.4

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pocmo**
## Proposed changes

This PR updates selenium to the latest version and disables the search engine choice screen that Chrome may show in some locations (See screenshot in #1868).

## Testing

Tested locally with Chrome 127.0.6533.73.

## Issues fixed

Fixes #1868.

### CODE REVIEW

**Comment by bartekpacia** [comment]
Hi Sebastian, thank you!

**Review by bartekpacia — APPROVED** [review]

**Comment by pocmo** [comment]
The CI test errors seem unrelated. Since there are new commits, I will rebase the PR and hopefully the next run will be green.

**Comment by bartekpacia** [comment]
Yeah, we need to sort out CI. Don't worry about that.

**Comment by pocmo** [comment]
`MaestroCommandSerializationTest` failed again with `UnsupportedClassVersionError` errors. Those tests pass locally for me though.

**Comment by bartekpacia** [comment]
Do you use JDK8 to build&run locally?

**Comment by bartekpacia** [comment]
@pocmo Our minimum JDK is Java 8, but [Selenium requires Java 11 since v4.14.0](https://github.com/SeleniumHQ/selenium/blob/9c686a563cd9c6e3fe835139e8f43b94744b706b/java/CHANGELOG#L300). This means we cannot upgrade to version equal to, or higher than, [Selenium v4.14](https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.14.0). [Learn more here](https://www.selenium.dev/blog/2023/java-8-support).

**Comment by pocmo** [comment]
Ah, that makes sense. I'll update to `4.14` and will test whether I can get passed the screen anyways.

> Our minimum JDK is Java 8

Any chance that will change in the future?

**Comment by bartekpacia** [comment]
> Any chance that will change in the future?

It's likely, but not in the next few months. We see that many of our users are on Java 8.

**Comment by bartekpacia** [comment]
thanks a ton!

**Pull request merged**
