### PR TITLE
Add changelog for the new, not-yet-released version

### PR DESCRIPTION
**Pull request by bartekpacia**

### CODE REVIEW

**Review by axelniklasson — APPROVED** [review]

**Comment by bartekpacia** [comment]
@tokou fyi: the changelog test if failing

**Comment by bartekpacia** [comment]
@tokou Ah, it's failing because I retroactively changed the changelog for v1.38.1. So it's all fine.

**Comment by bartekpacia** [comment]
I don't like that changelog must now be written in a quite rigid way, to make sure it displays correctly in the CLI.

I believe a link to the latest version should suffice.

**Comment by tokou** [comment]
> I don't like that changelog must now be written in a quite rigid way, to make sure it displays correctly in the CLI.

@bartekpacia I back tested it with a lot of the older versions and it still shows something decent
Basically, it takes only the first level bullet points and ignores anything else, and changelog will always have those (and they're the most meaningful info)

**Comment by bartekpacia** [comment]
Yeah, I thought about this more and I agree with you.

**Pull request merged**
