### PR TITLE
Feature: eraseText command

### PR DESCRIPTION
**Pull request by dmitry-zaitsev**

### CODE REVIEW

**Review by Leland-Takamine — COMMENTED** [review]
Defaulting to 50 backspaces feels arbitrary. What if we go with `backspace` (single backspace) and `backspace: N` (N backspaces)? This is more precise of an API. "eraseText" feels a little weird to me semantically since it's not immediately clear what this maps to

**Comment by dmitry-zaitsev** [comment]
@Leland-Takamine I would like to stick to a non-eng friendly notation to make it more approachable. `backspace` feels like exposing internal implementation details

**Comment by Leland-Takamine** [comment]
I think backspace is a well-understood concept in general and still think the backspace API makes more sense. But leaving to you for the final call

**Review by Leland-Takamine — APPROVED** [review]

**Comment by dmitry-zaitsev** [comment]
@Leland-Takamine we could introduce an alias as well, but perhaps it could make it more confusion. What do you think?

**Pull request merged**
