### PR TITLE
Fix device selection

### LINKED ISSUE #1849: Cannot choose which device to run on when multiple devices are running
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

Steps to reproduce:
1. Open multiple devices e.g. x1 iOS simulator & x1 Android Emulator.
2. Run the `maestro test yourFlow.yaml` command.
3. Observe no `Multiple running devices detected. Choose a device to run on.` prompt.

### Actual results

When I have multiple device running, I cannot select which device to run the flow on with the `maestro test` command anymore.

### Expected results

When I have multiple device running, I should be prompted with the terminal prompt:
```
Multiple running devices detected. Choose a device to run on.
Enter a number from the list above:
```
The `maestro studio` command still allows this functionality.

### About app

- Native iOS & Android app

### About environment

- MacBook Pro M2 Max - 32 GB
- macOS Sonoma 14.6
- arm64

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. *DO NOT* remove the backticks! -->
```

</details>

### Maestro version

1.37.4

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

### Anything else?

[1.36.0](https://github.com/mobile-dev-inc/maestro/releases/tag/cli-1.36.0) did not have this issue.
Occurred since [1.37.0](https://github.com/mobile-dev-inc/maestro/releases/tag/cli-1.37.0) release.

### PR DESCRIPTION
**Pull request by tokou**
## Proposed changes

- The issue seems to be in the logic related to selecting the devices depending on the shards
- I tried cleaning it up as best as  I could but that part of the code is kinda all over the place
- I started working on launching existing devices in addition to creating new ones for shards but I wonder what's the value from such a feature

## Testing

- Launch 2 devices
- Run a folder with multiple flows without specifying sharding
- Run a folder with multiple flows with shards = 2
- Run a folder with multiple flows with shards = 3

## Issues fixed

Fixes #1849

### CODE REVIEW

**Comment by bartekpacia** [comment]
Another false positive of #2005...

Screenshot 2024-09-03 at 12 02 48

**Comment by bartekpacia** [comment]
I tested this and it seems the issue is not fixed, i.e. Maestro still doesn't ask what device to run on when more than 1 device is connected.

To reproduce, start 2 android emulators, and then:

```
./maestro-cli/build/install/maestro/bin/maestro test --include-tags passing,failing --exclude-tags ios e2e/workspaces/demo_app
```

**Comment by bartekpacia** [comment]
Aside from that it looks good. Also thanks a ton for resolving all merge conflicts!

**Comment by bartekpacia** [comment]
Ugh, more conflicts after I merged #1995

**Comment by bartekpacia** [comment]
> I started working on launching existing devices in addition to creating new ones for shards but I wonder what's the value from such a feature

I think it's OK to not do this.

Actually, I don't like that Maestro CLI can create new devices as part of `maestro test`. In my opinion, to keep code cleaner and responsibilities separate, `maestro test` should merely print "Not enough devices. Start some or create with `maestro start-device`" instead of offering the user to go through the device creation flow.

**Comment by tokou** [comment]
Yeah I fully agree
But the feature was present that's why I kept it. I'll gladly get rid of that part of the code

**Comment by tokou** [comment]
@bartekpacia I got rid of device creation. I also switched `--shard-all` to a boolean as it makes more sense to me like that. Let me know what you think.

**Comment by bartekpacia** [comment]
This is awesome. Thank you.

**Comment by DavidREntwistle** [comment]
This fix doesn't look to have resolved [issue](https://github.com/mobile-dev-inc/maestro/issues/1849) in CLI  v. 1.39.0.
I'll re-raise [this](https://github.com/mobile-dev-inc/maestro/issues/1849) issue now.

**Pull request merged**
